### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by slashvalkyrie**
I created new icons that don't stick out so much against the rest of the macOS desktop. The menubar icon has been set to render as a template and will automatically switch colors as the menubar does.

### CODE REVIEW

**Comment by SeizureSaladd** [comment]
I'll be checking these later. The icon can be quite hard to see on the menu bar so this pull request is greatly appreciated.

**Comment by SeizureSaladd** [comment]
I am stupid and have appeared to forget that I can see these on mobile. I personally don't think the color theme matches but I'll look into it further tomorrow.

**Comment by slashvalkyrie** [comment]
What colors would you want?

**Comment by SeizureSaladd** [comment]
Preferably something closer to what we have now. I don't think the icon is the thing of most importance however.

**Comment by slashvalkyrie** [comment]
What do you mean closer to what you have now? The current icon is black and white

**Comment by SeizureSaladd** [comment]
Yeah which is what I mean

**Pull request closed without merging**
