### PR TITLE
Add more comprehensive and detailed documentation of the FPS unlocker.

### PR DESCRIPTION
**Pull request by YousufSSyed**
I rewrote the instructions so that instead of going to the location in terminal and then running it with two commands, users can place the file anywhere, copy the file path, and run it with only one command. I also added how to run the command using terminal aliases and using the Shortcuts app.

### CODE REVIEW

**Comment by SeizureSaladd** [comment]
Cool stuff, thank you.

**Comment by stevespog** [comment]
When I open Roblox and choose a fps cap the fpsunlocker app automatically crashes, any fixes to this?

**Comment by stevespog** [comment]
Oh, nevermind, its just that the cap can't go past 120 so the options higher than 120 are basically useless.

**Comment by SeizureSaladd** [comment]
it can't go past 120 due to vsync and you can disable that cap using quartz debug

**Comment by stevespog** [comment]
> 
Quartz Debug doesn't work for me

**Comment by DIOroa** [comment]
Every time I try to use it it crashes

**Pull request merged**
